### ISSUE TITLE
Harvesting - Errors setting up vrf and remote keys

### ISSUE THREAD

**Issue by meyns** [symbol/desktop-wallet#1328] opened 2021-03-17 06:21 UTC
I'm having trouble setting up a vrf and voting key: (my account is a 2of2 multisig account with 3 cosigs)
Trying to set up Remote and VRF keys using the symbol desktop wallet (not the 'Link all keys' but individually linking the remote and vrf key) gets me this error and a funds lock that doesn't do anything
Errors:
1. Validation failed because hash is not present in cache
2. Failed to sign transaction, reason: Failure_LockHash_Unknown_Hash

Funds lock transaction: http://explorer.symbolblockchain.io/transactions/7165F34C65DB4387BFD363C656E61EFABBD841B0831F9E0F6540855C31AF2B13

**Comment by surekabpm** [comment] 2021-03-31 07:42
I tried to replicate the issue in testnet with 3 cosigners, and i can link the VRF and remote keys manually , i did'nt see any issue.I'm using windows 
![image](https://user-images.githubusercontent.com/49143210/113108483-aafa3600-9222-11eb-95d4-ea7420658e5f.png)

**Comment by cryptoBeliever** [comment] 2021-06-05 16:45
Bug still exists.

1. Create 2of2 multisig
2. Choose cosigner account
3. Go to harvesting
4. Switch to multisig
5. Open "Key Links" tab
6. Add Remote Key by "Generate" and Confirm

Result:

Validation failed because hash is not present in cache
Failed to sign transaction, reason: Failure_LockHash_Unknown_Hash

**Comment by bassemmagdy** [comment] 2021-08-04 01:57
@cryptoBeliever @meyns is this reproducible in the latest version?

**Comment by cryptoBeliever** [comment] 2021-08-04 05:10
Seems to be already fixed in 1.0.5
I'm closing this one.

**Closed by cryptoBeliever** 2021-08-04 05:10 UTC
Labels: P2 Issue, harvesting
