### ISSUE TITLE
Error when installing on Debian: Some dependencies are missing

### ISSUE THREAD

**Issue by mm-s** [symbol/desktop-wallet#998] opened 2021-01-31 13:10 UTC
System:
```
Linux 5.10.0-1-amd64 #1 SMP Debian 5.10.5-1 (2021-01-09) x86_64 GNU/Linux
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
```

Reproduce:
<pre>
<b>wget https://github.com/nemgrouplimited/symbol-desktop-wallet/releases/download/v0.13.8/symbol-desktop-wallet-linux-amd64-0.13.8.deb

sudo dpkg -i symbol-desktop-wallet-linux-amd64-0.13.8.deb</b>

Selecting previously unselected package symbol-desktop-wallet.
(Reading database ... 201820 files and directories currently installed.)
Preparing to unpack symbol-desktop-wallet-linux-amd64-0.13.8.deb ...
Unpacking symbol-desktop-wallet (0.13.8) ...
dpkg: dependency problems prevent configuration of symbol-desktop-wallet:
 symbol-desktop-wallet depends on libappindicator3-1; however:
  Package libappindicator3-1 is not installed.

dpkg: error processing package symbol-desktop-wallet (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.68) ...
Errors were encountered while processing:
 symbol-desktop-wallet
</pre>

Workaround:
<pre>
<b>apt --fix-broken install</b>
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libappindicator3-1 libindicator3-7
The following NEW packages will be installed:
  libappindicator3-1 libindicator3-7
0 upgraded, 2 newly installed, 0 to remove and 31 not upgraded.
1 not fully installed or removed.
Need to get 106 kB of archives.
After this operation, 217 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main amd64 libindicator3-7 amd64 0.5.0-4 [52.9 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 libappindicator3-1 amd64 0.4.92-7 [53.5 kB]
Fetched 106 kB in 0s (1,113 kB/s)        
Selecting previously unselected package libindicator3-7:amd64.
(Reading database ... 201906 files and directories currently installed.)
Preparing to unpack .../libindicator3-7_0.5.0-4_amd64.deb ...
Unpacking libindicator3-7:amd64 (0.5.0-4) ...
Selecting previously unselected package libappindicator3-1:amd64.
Preparing to unpack .../libappindicator3-1_0.4.92-7_amd64.deb ...
Unpacking libappindicator3-1:amd64 (0.4.92-7) ...
Setting up libindicator3-7:amd64 (0.5.0-4) ...
Setting up libappindicator3-1:amd64 (0.4.92-7) ...
Setting up symbol-desktop-wallet (0.13.8) ...
</pre>

Guessed Resolution:
Include missing dependency in deb package

**Comment by cryptoBeliever** [comment] 2021-02-02 18:41
Looks like on Ubuntu I got this dependency already installed. Still for verification.

**Comment by rg911** [comment] 2021-02-02 23:59
@mm-s in fact if you have time perhaps you can have a look at this one?

**Comment by coiki** [comment] 2021-06-10 12:06
User Story: “As a user that wants to install the wallet for Debian, I want all needed dependencies to be installed, so I don’t need to download them through other methods.”

Acceptance Criteria:
- AC1: When installing on Debian, there are no issues with the installation and I can start using the wallet immediately.

**Comment by coiki** [comment] 2021-06-10 12:08
@cryptoBeliever Did we ever receive confirmation about if Electron requires this package? Can we confirm that installations on Debian are not working or it’s an isolated case? Thank you.

**Comment by cryptoBeliever** [comment] 2021-06-16 18:52
@coiki I think most of the distributions has it installed by default because we did not receive such reports. If it's possible to include it I think it should be. As far as I can see Oleg added this dependency.

**Comment by coiki** [comment] 2021-06-21 08:29
Let's close this task as 'Can't reproduce' if by the end of the sprint we don't see this issue again.

**Comment by cryptoBeliever** [comment] 2021-06-21 08:32
@coiki @OlegMakarenko already created draft pull request for that https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1031

**Comment by surekabpm** [comment] 2021-06-24 06:18
Added Alfonso's comment from JIRA 
Couldn’t reproduce again. No reports either from community or social.

**Comment by cryptoBeliever** [comment] 2021-06-25 20:51
Ok. So I'm closing.

**Comment by coiki** [comment] 2021-08-04 08:50
Reopening task due to a pull request that would fix this, which means this was reproduced by @OlegMakarenko 

@cryptoBeliever @AnthonyLaw will make sure that this is passed on forward.

**Comment by cryptoBeliever** [comment] 2021-08-09 21:06
After some reading, for example https://linuxhint.com/install-dpkg-dependencies-automatically/
dpkg does not install dependencies by default (this is how it works).

In X Server interface when you double click it's handled by the software center and it installed correctly dependencies.

As I understand change made by @OlegMakarenko  (https://github.com/symbol/desktop-wallet/pull/1031/files) will not fix that because it marks only dependencies that are already discovered by dpkg anyway. Please correct me if I'm wrong.

**Comment by cryptoBeliever** [comment] 2021-08-10 05:30
Considering the above I'm closing. If someone is more knowledgeable about deb packages please comment.

**Comment by cryptoBeliever** [comment] 2021-08-10 05:40
Considering above I'm closing.

**Closed by cryptoBeliever** 2021-08-10 05:40 UTC
Labels: P3 Issue
