### ISSUE TITLE
Aggregate transactions get random names from the addressbook 

### ISSUE THREAD

**Issue by NikoCyber** [symbol/desktop-wallet#1831] opened 2022-01-19 08:56 UTC
WTR:

1. Add some contacts in your addressbook
2. Send a few aggregate transactions from the same address to yours

Result: you can see that some transactions have random names from your addressbook 

On the screen below all unconfirmed aggregate transactions should have name `Paul`

**History Page**
![image](https://user-images.githubusercontent.com/11311924/150096689-44edd656-fbb3-419f-8c66-f02db3bc9508.png)

**Addressbook**
![image](https://user-images.githubusercontent.com/11311924/150096843-896323be-1dc1-4593-988b-c9dc47ea2861.png)

![image](https://user-images.githubusercontent.com/11311924/150096983-8e29a242-6979-4726-8d4b-d150756854ee.png)

**Comment by bassemmagdy** [comment] 2022-01-19 15:07
couldn't reproduce, please provide exported address book list and private key.

**Comment by bassemmagdy** [comment] 2022-01-21 02:44
The issue is not related to address-book changes, it's related to filters in general so we can fix that in a separate PR apart from #1814.

**Comment by cryptoBeliever** [comment] 2022-02-14 18:30
A similar problem is when I receive new bonded/unconfirmed transactions. Then looks like the name from the address book is taken from the confirmed transaction below unconfirmed:
https://share.getcloudapp.com/kpu4rD7z

**Comment by cryptoBeliever** [comment] 2022-02-17 15:24
Fixed in https://github.com/symbol/desktop-wallet/pull/1847

**Comment by cryptoBeliever** [comment] 2022-02-20 17:32
Fixed in https://github.com/symbol/desktop-wallet/pull/1847

**Comment by cryptoBeliever** [comment] 2022-09-19 21:31
Released (1.0.11)

**Closed** 2022-09-19 21:31 UTC
Labels: P2 Issue
